# Generated by Django 4.2 on 2023-04-18 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('email', models.CharField(blank=True, max_length=40, null=True)),
                ('mensagem', models.CharField(max_length=30)),
            ],
        ),
    ]
